remote_theme: kitbashery/just-the-docs

title: kitbashery.com

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# External navigation links
nav_external_links:
  - title: Kitbashery on GitHub
    url: https://github.com/Kitbashery
    hide_icon: false # set to true to hide the external link icon - defaults to false
    
 - title: Kitbashery on Discord
    url: 
    hide_icon: false
    
- title: Kitbashery on Unity Asset Store
    url: 
    hide_icon: false
    
 - title: Commission a Feature
    url: 
    hide_icon: false
    
- title: Leave a Tip
    url: 
    hide_icon: false
