remote_theme: kitbashery/just-the-docs

title: kitbashery.com

# Color scheme supports "light" (default) and "dark"
color_scheme: kitbashery

# External navigation links
nav_external_links:
  - title: Kitbashery on GitHub
    url: https://github.com/Kitbashery
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Kitbashery on Discord
    url: https://discord.gg/3vjtMneeFv
    hide_icon: false
  - title: Unity Asset Store
    url: https://assetstore.unity.com/publishers/72943
    hide_icon: false
  - title: Commission a Feature
    url: https://ko-fi.com/kitbashery/commissions
    hide_icon: false
